
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-nim-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: k8s-nim-operator
      repoURL: 'https://helm.ngc.nvidia.com/nvidia'
      targetRevision: "1.0.1"
      helm:
        releaseName: k8s-nim-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-nim-operator
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
