
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volcano
  namespace: argocd
spec:
  project: default
  source:
    chart: volcano
    repoURL: 'https://volcano-sh.github.io/helm-charts'
    targetRevision: "1.9.0"
    helm:
      releaseName: volcano
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: volcano
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
