
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - chart: minio
      repoURL: 'registry-1.docker.io/bitnamicharts'
      targetRevision: "14.6.33"
      helm:
        releaseName: minio-client
        valuesObject:
          global:
            defaultStorageClass: standard
          auth:
            existingSecret: "existing-minio-auth-secret"
            rootUserSecretKey: "username"
            rootPasswordSecretKey: "password"
            mode: standalone
            persistence:
              enabled: true
              size: 20Gi
              storageClass: "standard"
              annotations:
                helm.sh/resource-policy: keep
    - repoURL: 'ssh://git@github.com/tedtollefson/llmops-nvidia.git'
      path: secrets/minio
      targetRevision: main
      directory:
        recurse: true   
    - repoURL: 'ssh://git@github.com/tedtollefson/llmops-nvidia.git'
      path: ingress/minio
      targetRevision: main
      directory:
        recurse: true  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
