
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama3-1-8b-instruct
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'ssh://git@github.com/tedtollefson/llmops-nvidia.git'
      path: secrets/nvcr
      targetRevision: main
      directory:
        recurse: true  
    - repoURL: 'ssh://git@github.com/tedtollefson/llmops-nvidia.git'
      path: k8s-manifests/llama3-1-8b-instruct
      targetRevision: main
      directory:
        recurse: true  
    - repoURL: 'ssh://git@github.com/tedtollefson/llmops-nvidia.git'
      path: ingress/llama3-1-8b-instruct
      targetRevision: main
      directory:
        recurse: true 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: llama3-1-8b-instruct
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
